
export const  ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const  ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const  ADD_CART_FAIL = "ADD_CART_FAIL"
export const  ADD_CART_NULL = "ADD_CART_NULL"

export const  ADD_CART_LIST_REQUEST = "ADD_CART_LIST_REQUEST"
export const  ADD_CART_LIST_SUCCESS = "ADD_CART_LIST_SUCCESS"
export const  ADD_CART_LIST_FAIL = "ADD_CART_LIST_FAIL"