
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST"
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS"
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL"

export const PRODUCT_getTarget_REQUEST = "PRODUCT_getTarget_REQUEST"
export const PRODUCT_getTarget_SUCCESS = "PRODUCT_getTarget_SUCCESS"
export const PRODUCT_getTarget_FAIL = "PRODUCT_getTarget_FAIL"

